---
- hosts: master_node
  become: yes
  tasks:
    - name: Turn off swap
      shell: sed -i -e '/swap/d' /etc/fstab >> swapoff.txt
      args:
        creates: swapoff.txt
         
    - name: initialize the cluster
      shell: kubeadm init --pod-network-cidr=10.244.0.0/16 >> cluster_initialized.txt
      args:
        chdir: $HOME
        creates: cluster_initialized.txt

    - name: create .kube directory
      become: yes
      become_user: ubuntu
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ubuntu/.kube/config
        remote_src: yes
        owner: ubuntu

    - name: Untaint node
      become: yes
      become_user: ubuntu
      shell: kubectl taint nodes --all node-role.kubernetes.io/control-plane- >> taint.txt
      args:
        chdir: $HOME
        creates: taint.txt

    - name: install Pod network
      become: yes
      become_user: ubuntu
      shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml >> pod_network_setup.txt
      args:
        chdir: $HOME

        creates: pod_network_setup.txt