---
- hosts: master_node
  become: yes
  tasks:

  # This playbook uses containerd for the container runtime. 
  # https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#installing-runtime

  # containerd runtime package is distrubuted by docker and is bundle with docker.io
  #  https://github.com/containerd/containerd/blob/main/docs/getting-started.md#option-2-from-apt-get-or-dnf
   - name: install Docker
     apt:
       name: docker.io
       state: present
       update_cache: true

   - name: create Docker config directory
     file: path=/etc/docker state=directory

   - name: install APT Transport HTTPS
     apt:
       name: apt-transport-https
       state: present

   - name: install ca-certificates
     apt:
       name: ca-certificates
       state: present

   - name: install curl
     apt:
       name: curl
       state: present

   - name: install gpg
     apt:
       name: gpg
       state: present 
  
   - name: Install k8s public signing key
     ansible.builtin.shell: curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
     args:
      executable: /bin/bash
      creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

   - name: Update apt sources
     ansible.builtin.shell: echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /' | tee /etc/apt/sources.list.d/kubernetes.list
     args:
      executable: /bin/bash

   - name: install kubelet
     apt:
       name: kubelet
       state: present
       update_cache: true

   - name: install kubeadm
     apt:
       name: kubeadm
       state: present

   - name: install kubectl
     apt:
       name: kubectl
       state: present